export const REACT_APP_SHOPEE_PARTNER_ID = process.env.REACT_APP_SHOPEE_PARTNER_ID;
export const REACT_APP_SHOPEE_PARTNER_KEY = process.env.REACT_APP_SHOPEE_PARTNER_KEY;
export const REACT_APP_SHOPEE_API_BASE_URL = process.env.REACT_APP_SHOPEE_API_BASE_URL;
